export { default as Landing } from './landing/Landing'
export { default as Login } from './login/Login'
export { default as CreateBrands } from './createBrand/CreateBrand'
export { default as BrandSummary } from './brandSummary/BrandSummary'
export { default as SuppDataCategory } from './suppDataCategory'
export { default as SuppDataRetailers } from './suppDataRetailers'
export { default as SuppDataPrice} from './suppDataPrice'
export { default as SuppDataGender } from './suppDataGender'
export { default as SuppDataSimilarBrands } from './suppDataSimilarBrands'
export { default as BrandFormContainer } from './brandFormsContainer'
export { default as BrandLanding } from './brandLanding'
export { default as BrandSentences } from './brandSentences'
export { default as SuppDataTypes } from './suppDataTypes'
export { default as SuppDataAlias } from './suppDataAlias'
export { default as SuppDataStyles } from './suppDataStyles'
