export { default as Header } from './header/Header'
export { default as Footer } from './footer/Footer'
export { default as ProgressBar } from './progressBar/ProgressBar'
export { default as Brand } from './brand/Brand'
export { default as SummaryHeader } from './summaryHeader/SummaryHeader'
export { default as SummaryBrandOverview } from './summaryBrandOverview/SummaryBrandOverview'
export { default as SummaryRating } from './summaryRating/SummaryRating'
export { default as SummaryQualitativeRating } from './summaryQualitativeRating/SummaryQualitativeRating'
export { default as SummarySupplementaryData } from './summarySupplementaryData/SummarySupplementaryData'
export { default as OverviewHeading } from './overviewHeading'
export { default as RatingHeading } from './ratingHeading'
export { default as QualiHeading } from './qualiHeading'
export { default as SuppHeading } from './suppHeading'
export { default as Price } from './price/price'

export const url = /^((http|https)?:\/\/)?([\da-z\.-]+)\.([a-z\.]{2,6})([\/\w \.-]*)*\/?$/
